sudo: true
language: php
php:
    - 5.6
    - 7.0
    - 7.1
env:
    - LIBRDKAFKA_VERSION=0.8
    - LIBRDKAFKA_VERSION=0.11.0.x
    - LIBRDKAFKA_VERSION=0.11.1.x
    - LIBRDKAFKA_VERSION=0.11.x
    - LIBRDKAFKA_VERSION=master
script: ./travis.sh
